version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '80:27017'
  
  api:
    container_name: 'quiz-api'
    restart: always
    build: '.'
    ports:
      - '8080:8080'
    links:
      - 'mongo'

  