info: {}
paths:
  /auth/login:
    post:
      description: Login a user
      operationId: login
      tags:
      - auth
  /auth/register:
    post:
      description: Registers a user
      operationId: register
      tags:
      - auth
  /quiz:
    get:
      description: Returns a list of quizes
      operationId: listQuiz
      tags:
      - quiz
    post:
      description: Create a new quiz
      operationId: createQuiz
      tags:
      - quiz
  /quiz/{id}:
    delete:
      description: Delete a quiz
      operationId: deleteQuiz
      tags:
      - quiz
    get:
      description: Returns a single quiz
      operationId: singleQuiz
      tags:
      - quiz
    put:
      description: Update a quiz
      operationId: updateQuiz
      tags:
      - quiz
  /user:
    get:
      description: Returns a list of users
      operationId: listUser
      tags:
      - user
    post:
      description: Create a new user
      operationId: createUser
      tags:
      - user
  /user/{id}:
    delete:
      description: Delete a user
      operationId: deleteUser
      tags:
      - user
    get:
      description: Returns a single user
      operationId: singleUser
      tags:
      - user
    put:
      description: Update a users details
      operationId: updateUser
      tags:
      - user
swagger: "2.0"
