version: '3'
services: 
  mongo:
    image: mongo:3.6.19-xenial
    ports: 
      - "27017:27017"
    networks: 
      - quiz
    volumes: 
      - mongo-data:/data/db
  
  api:
    restart: always
    build: '.'
    networks: 
      - quiz
    ports: 
      - '8080:8080'
    depends_on: 
      - mongo

networks: 
  quiz:
    driver: bridge
volumes: 
  mongo-data:
    driver: local